#!/bin/bash

# define the lid switch actions
source /etc/default/aclidswitch

# set by 60-aclidswitch.rules & 99-low-battery-action.rules
case "$1" in 

battery)
    sed -i "s/^.*\bHandleLidSwitch\b.*$/HandleLidSwitch=$LID_SWITCH_ACTION_BAT/" /etc/systemd/logind.conf
    systemctl restart systemd-logind
    light=$(/usr/bin/light -G | grep -Eo '^[0-9]+')
    if [ $light -gt $BRIGHTNESS_BAT ] ; then
	    /usr/bin/light -S $BRIGHTNESS_BAT 
    fi

    for DPMS in "${DPMS_BAT[@]}"
    do 
        $DPMS
    done
    
    for SERVICE in $SYSTEMD_BAT
    do
        systemctl stop $SERVICE
    done
    ;;
AC)
    sed -i "s/^.*\bHandleLidSwitch\b.*$/HandleLidSwitch=$LID_SWITCH_ACTION_AC/" /etc/systemd/logind.conf
    systemctl restart systemd-logind
    light=$(/usr/bin/light -G | grep -Eo '^[0-9]+')
    if [ $light -lt $BRIGHTNESS_AC ] ; then
	    /usr/bin/light -S $BRIGHTNESS_AC 
    fi

    for DPMS in "${DPMS_AC[@]}"
    do 
        $DPMS
    done
    
    for SERVICE in $SYSTEMD_AC
    do
        systemctl restart $SERVICE
    done
    ;;
lowbat)
    systemctl $LOW_BAT_ACTION
    ;;
esac
